//
//  swift_files.c
//  exp2swift
//
//  Created by Yoshida on 2020/06/13.
//  Copyright © 2020 Minokamo, Japan. All rights reserved.
//

#include <stdlib.h>
#include <errno.h>
#include <sc_mkdir.h>


#include <sc_version_string.h>
#include <express/express.h>

#include <exppp/exppp.h>
#include "pp.h"


#include "swift_files.h"
#include "swift_schema.h"
#include "swift_type.h"
#include "swift_entity.h"

const int nestingIndent_swift = 2;       /* default nesting indent */

void beginExpress_swift(char* description) {
	raw( "//MARK: -%s in EXPRESS\n/*\n", description );
}

void endExpress_swift() {
	raw( "\n*/\n\n" );
}

void indent_swift(int level) {
	if( level <= 0 ) return;
	raw( "%*s", level, "");
}

//char * exppp_output_filename = ( char * )0; /* if this is set, override default output filename */
static char swift_filename_buffer[1000];           /* output file name */

/* Only the first line is compared to an existing file, so putting a
 * version number in here won't cause problems. The actual version must
 * be inserted later - this can't be initialized with non-constant.
 */
static char * expheader[] = {
    "/* This file was generated by the EXPRESS to Swift translator \"exp2swift\",",
    "derived from STEPcode (formerly NIST's SCL).\n",
		"exp2swift version:","",/*version string to be inserted here*/"", "\n",
    "WARNING: You probably don't want to edit it since your modifications",
		"will be lost if exp2swift is used to regenerate it.\n",
		"*/\n\n"                     ,
    0
};


void closeSwiftFile(void) {
	if( exppp_fp != NULL ) {
		fclose( exppp_fp );
	}
	exppp_fp = NULL;
}


static void printOutHeaderComment() {
	char ** hp;
	error_sym.line = 1;
	/* print our header - generated by exppp, don't edit, etc */
	for( hp = expheader; *hp; hp++ ) {
		if( ( **hp == '\0' ) && ( **( hp + 1 ) == '\0' ) ) {
			/* if this and the next lines are blank, put version string on this line */
			wrap( "%s ", sc_version );
		} else {
			wrap( "%s ", *hp );
		}
	}
}

static bool described = false;

void openSwiftFileForSchema(Schema schema) {
	
	FILE * f;
	closeSwiftFile();
	exppp_output_filename = 0;
	
	exppp_output_filename = swift_filename_buffer;
	exppp_output_filename_reset = true;
	sprintf( swift_filename_buffer, "%s.swift", SCHEMA_swiftName(schema) );
	
	error_sym.filename = swift_filename_buffer;
	
	if( !described && !exppp_terse ) {
		fprintf( stdout, "%s: writing schema file %s\n", EXPRESSprogram_name, swift_filename_buffer );
	}
	if( !( exppp_fp = f = fopen( swift_filename_buffer, "w" ) ) ) {
		ERRORreport( ERROR_file_unwriteable, swift_filename_buffer, strerror( errno ) );
		abort();
	}
	
	printOutHeaderComment();
}

static char dir[ BUFSIZ ] = {0};

void openSwiftFileForType(Type type) {
	
	FILE * f;
	closeSwiftFile();
	exppp_output_filename = 0;
	
	exppp_output_filename = swift_filename_buffer;
	exppp_output_filename_reset = true;
	snprintf( dir, BUFSIZ-1, "type/%c", TYPE_swiftNameInitial(type) );
	sprintf( swift_filename_buffer, "%s/%s.swift", dir, TYPE_swiftName(type) );
	
	error_sym.filename = swift_filename_buffer;
	
	if( !described && !exppp_terse ) {
		fprintf( stdout, "%s: writing schema file %s\n", EXPRESSprogram_name, swift_filename_buffer );
	}
	
	if( mkDirIfNone( "type" ) == -1 ) {
			fprintf( stderr, "At %s:%d - mkdir() failed with error ", __FILE__, __LINE__);
			perror( 0 );
			abort();
	}
	if( mkDirIfNone( dir ) == -1 ) {
			fprintf( stderr, "At %s:%d - mkdir() failed with error ", __FILE__, __LINE__);
			perror( 0 );
			abort();
	}

	
	if( !( exppp_fp = f = fopen( swift_filename_buffer, "w" ) ) ) {
		ERRORreport( ERROR_file_unwriteable, swift_filename_buffer, strerror( errno ) );
		abort();
	}
	
	printOutHeaderComment();
}

void openSwiftFileForEntity(Entity entity) {
	
	FILE * f;
	closeSwiftFile();
	exppp_output_filename = 0;
	
	exppp_output_filename = swift_filename_buffer;
	exppp_output_filename_reset = true;
	snprintf( dir, BUFSIZ-1, "entity/%c", ENTITY_swiftNameInitial(entity) );
	sprintf( swift_filename_buffer, "%s/%s.swift", dir, ENTITY_swiftName(entity) );
	
	error_sym.filename = swift_filename_buffer;
	
	if( !described && !exppp_terse ) {
		fprintf( stdout, "%s: writing schema file %s\n", EXPRESSprogram_name, swift_filename_buffer );
	}
	
	if( mkDirIfNone( "entity" ) == -1 ) {
			fprintf( stderr, "At %s:%d - mkdir() failed with error ", __FILE__, __LINE__);
			perror( 0 );
			abort();
	}
	if( mkDirIfNone( dir ) == -1 ) {
			fprintf( stderr, "At %s:%d - mkdir() failed with error ", __FILE__, __LINE__);
			perror( 0 );
			abort();
	}

	
	if( !( exppp_fp = f = fopen( swift_filename_buffer, "w" ) ) ) {
		ERRORreport( ERROR_file_unwriteable, swift_filename_buffer, strerror( errno ) );
		abort();
	}
	
	printOutHeaderComment();
}
